<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Batch extends Model
{
    protected $table = 'batches';

    protected $fillable = ['batch_name', 'batch_description'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->batch_description = "I am Mock Data!";
        });
    }

    public function getBatchDescriptionAttribute()
    {
        if ($this->attributes['batch_description'] == 1) {
            return "男";
        } else {
            return "女";
        }
    }

    public function getBatchDescription()
    {
        return $this->attributes['batch_description'];
    }
}
